substitutions:
  name: ogt-bms-ble
  device_description: "Monitor a Offgridtec Battery Management System via BLE"
  external_components_source: github://syssi/esphome-ogt-bms@main
  mac_address: !secret bms0_mac_address
  ble_name: !secret bms0_ble_name

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-ogt-bms"
    version: 1.1.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${mac_address}
    id: client0

ogt_bms_ble:
  - ble_client_id: client0
    id: bms0
    ble_name: ${ble_name}
    update_interval: 10s

binary_sensor:
  - platform: ogt_bms_ble
    ogt_bms_ble_id: bms0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

button:
  - platform: ogt_bms_ble
    ogt_bms_ble_id: bms0
    retrieve_serial_number:
      name: "${name} retrieve serial number"
    retrieve_manufacture_date:
      name: "${name} retrieve manufacture date"

sensor:
  - platform: ogt_bms_ble
    ogt_bms_ble_id: bms0
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    state_of_charge:
      name: "${name} state of charge"
    charging_cycles:
      name: "${name} charging cycles"
    capacity_remaining:
      name: "${name} capacity remaining"
    design_capacity:
      name: "${name} design capacity"
    full_charge_capacity:
      name: "${name} full charge capacity"
    mosfet_temperature:
      name: "${name} mosfet temperature"
    time_to_empty:
      name: "${name} time to empty"
    time_to_full:
      name: "${name} time to full"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"
    id: ble_client_switch0

text_sensor:
  - platform: ogt_bms_ble
    ogt_bms_ble_id: bms0
    time_to_empty_formatted:
      name: "${name} time to empty formatted"
    time_to_full_formatted:
      name: "${name} time to full formatted"
    serial_number:
      name: "${name} serial number"
    manufacture_date:
      name: "${name} manufacture date"
